# Generated by Django 3.0.5 on 2020-04-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Mobnum', models.CharField(max_length=15)),
                ('Company', models.CharField(max_length=15)),
            ],
        ),
    ]
