# Generated by Django 3.0.5 on 2020-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Company',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Mobnum',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
