# Generated by Django 3.0.5 on 2020-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20200413_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Mobnum',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
