# Generated by Django 3.0.5 on 2020-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_auto_20200413_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Company',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
